### ISSUE TITLE
Crash of `embObjMotionControl` on closure of `yarprobotinterface`

### ISSUE THREAD

**Issue by Nicogene** [robotology/icub-main#962] opened 2024-05-29 14:08 UTC
### Bug description

Today w/ @martinaxgloria we noticed on `iCubGenova11` that w/ `icub-main` on latest devel `yarprobotinterface` crashes on closure.
The faulty plugin is `embObjMotionControl`.

### Steps to reproduce

Run `yarprobotinterface` and close it.

### Expected behavior

It does not crashes in closure

### Additional context

This issue is probably breaking the `robots-configuration` CI
- https://github.com/robotology/robots-configuration/actions/runs/9284133798/job/25545849005

cc @valegagge @MSECode @pattacini @marcoaccame

**Comment by valegagge** [comment] 2024-05-29 14:13
Hi @Nicogene and @martinaxgloria , 
 Are you on top of devel? are you running YRI with the configuration on devel?

thanks heaps

**Comment by Nicogene** [comment] 2024-05-29 14:25
Yes both on latest devel, also `icub-firmware-shared`

**Comment by MSECode** [comment] 2024-05-29 14:25
I noticed it as well. One thing that I saw by working on different setups is that:
- on `ergoCub001`, which is slightly behind on the latest updates with respect to `devel` (on multiple repositories part of the superbuild), I did not notice any  `segmentation fault error` in closure
- on other setups, such as our upper-arm, and on `ergoCub002`, which are instead aligned with the latest updates, I noticed the `segmentation fault error` multiple times while closing the YRI.

It would be possible to start to analyze at which point in the git history we started to have such error.

**Comment by Nicogene** [comment] 2024-05-29 14:50
Looking at the [history](https://github.com/robotology/icub-main/commits/master/src/libraries/icubmod/embObjMotionControl), there are two potential commits:
- 03/2024 -> https://github.com/robotology/icub-main/commit/6376390d867d57ba4ae4e55fab4467a9a256b1e0
- 05/2024 -> https://github.com/robotology/icub-main/commit/5410ab082d5cf95109354e6cfd809a3324bc1d82

**Comment by pattacini** [comment] 2024-05-29 14:59
The crash was caught also by the latest robots-configuration CI:
- https://github.com/robotology/robots-configuration/actions/runs/9284133798/job/25545849005

**Comment by valegagge** [comment] 2024-05-29 17:05
> Looking at the [history](https://github.com/robotology/icub-main/commits/master/src/libraries/icubmod/embObjMotionControl), there are two potential commits:

The history you posted is for master and to for devel 😸 
> 
> * 03/2024 -> [6376390](https://github.com/robotology/icub-main/commit/6376390d867d57ba4ae4e55fab4467a9a256b1e0)

It seems a commit related to the parser mainly

> * 05/2024 -> [5410ab0](https://github.com/robotology/icub-main/commit/5410ab082d5cf95109354e6cfd809a3324bc1d82)
If I'm not mistaken here we didn't touch something related to some clean or deallocation task in embObjMotioncontrol closure.

We suspect something related to [this commit](https://github.com/robotology/icub-main/commit/9f14d25946fdf22e8efc342f23ff781af6def5b0).

**Comment by MSECode** [comment] 2024-05-29 17:16
Exactly. I've did not experienced any `segmentation fault error` using a setup with 2 medium joint made of 1 EMS + 1 2FOC, while I got that issue in some occasions while working with the setup of the full `upper arm`, which has a double amount of those components. 
I'll dig into the problem debugging on iCubGenova11 w/ @valegagge.

**Comment by MSECode** [comment] 2024-05-30 13:06
Working w/ @valegagge on `icubGenova11` we spotted the source of the problem at these lines: https://github.com/robotology/icub-main/blob/master/src/libraries/icubmod/embObjLib/ethBoards.cpp#L222-L225

Basically when we introduced [this fix](https://github.com/robotology/icub-main/pull/954) we perform wrongly the for loop in the method `bool eth::EthBoards::rem(eth::AbstractEthResource* res)` called at the removal of the resources managed by the devices when closing the YRI. Therefore, by looping over all the LUT at the first call of the `eth::EthBoards::rem()` method, we were performing the clearing of all the LUT when closing the first device in the list of calls. Thus, for all the subsequent calls was impossible to find the resource to remove, since it was not existing anymore.  
Therefore, to fix that we removed the outer loop, so that the `clear()` method is called for the only LUT we need to remove at that instant. 
The changes are visible at [these lines](https://github.com/MSECode/icub-main/blob/fix/coreDumpWhenClosing/src/libraries/icubmod/embObjLib/ethBoards.cpp#L222-L223)

As described above, now the issue is solved and here I leave yri log file and the screen showing that all devices are closed correctly:

[log-YRI.txt](https://github.com/robotology/icub-main/files/15500288/log-YRI.txt)

![Screenshot from 2024-05-30 14-35-34](https://github.com/robotology/icub-main/assets/77933235/98f0d3a0-e52b-4d43-8e51-76d4f7375f07)


Here the stack trace showing where the core was dumping

![Screenshot from 2024-05-30 13-42-22](https://github.com/robotology/icub-main/assets/77933235/1a63b71c-b35d-4c79-9279-243b9763cffd)

**Comment by pattacini** [comment] 2024-05-31 06:57
> The crash was caught also by the latest robots-configuration CI:
> 
> * https://github.com/robotology/robots-configuration/actions/runs/9284133798/job/25545849005

Reopening since I've still spotted problems with the CI:
- https://github.com/robotology/robots-configuration/actions/runs/9314074218

**Comment by pattacini** [comment] 2024-05-31 07:02
Hold on! Probably, the wrong icub-main version ended up in the docker image.

**Comment by pattacini** [comment] 2024-05-31 08:43
See #965.

**Closed by pattacini** 2024-05-31 08:43 UTC
Labels: Type: Bug
