### ISSUE TITLE
Installation fails due to stereoCalib on Ubuntu 18.04

### ISSUE THREAD

**Issue by prajval10** [robotology/icub-main#619] opened 2019-11-08 11:49 UTC
I followed the instructions from http://wiki.icub.org/wiki/Linux:Installation_from_sources#Getting_all_dependencies and the cmake options specified in the docs. I have errors as seen here:

```[console]
[ 52%] Building CXX object src/tools/stereoCalib/CMakeFiles/stereoCalib.di/src/stereoCalibThread.cpp.o
In file included from /home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv.h:60:0,
                 from /home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:2:
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:45:89: error: ‘CV_RGB2BGR’ was not declared in this scope
 template<> struct convert_code_to_cv<yarp::sig::PixelRgb> : std::integral_constant<int, CV_RGB2BGR> {};
                                                                                         ^~~~~~~~~~
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:45:89: note: suggested alternative: ‘CV_RGB’
 template<> struct convert_code_to_cv<yarp::sig::PixelRgb> : std::integral_constant<int, CV_RGB2BGR> {};
                                                                                         ^~~~~~~~~~
                                                                                         CV_RGB
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:45:99: error: template argument 2 is invalid
 template<> struct convert_code_to_cv<yarp::sig::PixelRgb> : std::integral_constant<int, CV_RGB2BGR> {};
                                                                                                   ^
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:46:95: error: ‘CV_RGB2BGR’ was not declared in this scope
 template<> struct convert_code_to_cv<yarp::sig::PixelRgbSigned> : std::integral_constant<int, CV_RGB2BGR> {};
                                                                                               ^~~~~~~~~~
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:46:95: note: suggested alternative: ‘CV_RGB’
 template<> struct convert_code_to_cv<yarp::sig::PixelRgbSigned> : std::integral_constant<int, CV_RGB2BGR> {};
                                                                                               ^~~~~~~~~~
                                                                                               CV_RGB
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:46:105: error: template argument 2 is invalid
 template<> struct convert_code_to_cv<yarp::sig::PixelRgbSigned> : std::integral_constant<int, CV_RGB2BGR> {};
                                                                                                         ^
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:47:94: error: ‘CV_RGB2BGR’ was not declared in this scope
 template<> struct convert_code_to_cv<yarp::sig::PixelRgbFloat> : std::integral_constant<int, CV_RGB2BGR> {};
                                                                                              ^~~~~~~~~~
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:47:94: note: suggested alternative: ‘CV_RGB’
 template<> struct convert_code_to_cv<yarp::sig::PixelRgbFloat> : std::integral_constant<int, CV_RGB2BGR> {};
                                                                                              ^~~~~~~~~~
                                                                                              CV_RGB
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:47:104: error: template argument 2 is invalid
 template<> struct convert_code_to_cv<yarp::sig::PixelRgbFloat> : std::integral_constant<int, CV_RGB2BGR> {};
                                                                                                        ^
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:48:92: error: ‘CV_RGB2BGR’ was not declared in this scope
 template<> struct convert_code_to_cv<yarp::sig::PixelRgbInt> : std::integral_constant<int, CV_RGB2BGR> {};
                                                                                            ^~~~~~~~~~
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:48:92: note: suggested alternative: ‘CV_RGB’
 template<> struct convert_code_to_cv<yarp::sig::PixelRgbInt> : std::integral_constant<int, CV_RGB2BGR> {};
                                                                                            ^~~~~~~~~~
                                                                                            CV_RGB
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:48:102: error: template argument 2 is invalid
 template<> struct convert_code_to_cv<yarp::sig::PixelRgbInt> : std::integral_constant<int, CV_RGB2BGR> {};
                                                                                                      ^
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:49:89: error: ‘CV_HSV2BGR’ was not declared in this scope
 template<> struct convert_code_to_cv<yarp::sig::PixelHsv> : std::integral_constant<int, CV_HSV2BGR> {};
                                                                                         ^~~~~~~~~~
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:49:89: note: suggested alternative: ‘CV_SSE2’
 template<> struct convert_code_to_cv<yarp::sig::PixelHsv> : std::integral_constant<int, CV_HSV2BGR> {};
                                                                                         ^~~~~~~~~~
                                                                                         CV_SSE2
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:49:99: error: template argument 2 is invalid
 template<> struct convert_code_to_cv<yarp::sig::PixelHsv> : std::integral_constant<int, CV_HSV2BGR> {};
                                                                                                   ^
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:50:94: error: ‘CV_HSV2BGR’ was not declared in this scope
 template<> struct convert_code_to_cv<yarp::sig::PixelHsvFloat> : std::integral_constant<int, CV_HSV2BGR> {};
                                                                                              ^~~~~~~~~~
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:50:94: note: suggested alternative: ‘CV_SSE2’
 template<> struct convert_code_to_cv<yarp::sig::PixelHsvFloat> : std::integral_constant<int, CV_HSV2BGR> {};
                                                                                              ^~~~~~~~~~
                                                                                              CV_SSE2
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:50:104: error: template argument 2 is invalid
 template<> struct convert_code_to_cv<yarp::sig::PixelHsvFloat> : std::integral_constant<int, CV_HSV2BGR> {};
                                                                                                        ^
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:51:90: error: ‘CV_RGBA2BGRA’ was not declared in this scope
 template<> struct convert_code_to_cv<yarp::sig::PixelRgba> : std::integral_constant<int, CV_RGBA2BGRA> {};
                                                                                          ^~~~~~~~~~~~
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:51:90: note: suggested alternative: ‘CV_RGB’
 template<> struct convert_code_to_cv<yarp::sig::PixelRgba> : std::integral_constant<int, CV_RGBA2BGRA> {};
                                                                                          ^~~~~~~~~~~~
                                                                                          CV_RGB
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:51:102: error: template argument 2 is invalid
 template<> struct convert_code_to_cv<yarp::sig::PixelRgba> : std::integral_constant<int, CV_RGBA2BGRA> {};
                                                                                                      ^
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:63:91: error: ‘CV_BGR2RGB’ was not declared in this scope
 template<> struct convert_code_from_cv<yarp::sig::PixelRgb> : std::integral_constant<int, CV_BGR2RGB> {};
                                                                                           ^~~~~~~~~~
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:63:91: note: suggested alternative: ‘CV_RGB’
 template<> struct convert_code_from_cv<yarp::sig::PixelRgb> : std::integral_constant<int, CV_BGR2RGB> {};
                                                                                           ^~~~~~~~~~
                                                                                           CV_RGB
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:63:101: error: template argument 2 is invalid
 template<> struct convert_code_from_cv<yarp::sig::PixelRgb> : std::integral_constant<int, CV_BGR2RGB> {};
                                                                                                     ^
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:64:97: error: ‘CV_BGR2RGB’ was not declared in this scope
 template<> struct convert_code_from_cv<yarp::sig::PixelRgbSigned> : std::integral_constant<int, CV_BGR2RGB> {};
                                                                                                 ^~~~~~~~~~
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:64:97: note: suggested alternative: ‘CV_RGB’
 template<> struct convert_code_from_cv<yarp::sig::PixelRgbSigned> : std::integral_constant<int, CV_BGR2RGB> {};
                                                                                                 ^~~~~~~~~~
                                                                                                 CV_RGB
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:64:107: error: template argument 2 is invalid
 template<> struct convert_code_from_cv<yarp::sig::PixelRgbSigned> : std::integral_constant<int, CV_BGR2RGB> {};
                                                                                                           ^
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:65:96: error: ‘CV_BGR2RGB’ was not declared in this scope
 template<> struct convert_code_from_cv<yarp::sig::PixelRgbFloat> : std::integral_constant<int, CV_BGR2RGB> {};
                                                                                                ^~~~~~~~~~
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:65:96: note: suggested alternative: ‘CV_RGB’
 template<> struct convert_code_from_cv<yarp::sig::PixelRgbFloat> : std::integral_constant<int, CV_BGR2RGB> {};
                                                                                                ^~~~~~~~~~
                                                                                                CV_RGB
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:65:106: error: template argument 2 is invalid
 template<> struct convert_code_from_cv<yarp::sig::PixelRgbFloat> : std::integral_constant<int, CV_BGR2RGB> {};
                                                                                                          ^
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:66:94: error: ‘CV_BGR2RGB’ was not declared in this scope
 template<> struct convert_code_from_cv<yarp::sig::PixelRgbInt> : std::integral_constant<int, CV_BGR2RGB> {};
                                                                                              ^~~~~~~~~~
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:66:94: note: suggested alternative: ‘CV_RGB’
 template<> struct convert_code_from_cv<yarp::sig::PixelRgbInt> : std::integral_constant<int, CV_BGR2RGB> {};
                                                                                              ^~~~~~~~~~
                                                                                              CV_RGB
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:66:104: error: template argument 2 is invalid
 template<> struct convert_code_from_cv<yarp::sig::PixelRgbInt> : std::integral_constant<int, CV_BGR2RGB> {};
                                                                                                        ^
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:67:91: error: ‘CV_BGR2HSV’ was not declared in this scope
 template<> struct convert_code_from_cv<yarp::sig::PixelHsv> : std::integral_constant<int, CV_BGR2HSV> {};
                                                                                           ^~~~~~~~~~
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:67:91: note: suggested alternative: ‘CV_32SC’
 template<> struct convert_code_from_cv<yarp::sig::PixelHsv> : std::integral_constant<int, CV_BGR2HSV> {};
                                                                                           ^~~~~~~~~~
                                                                                           CV_32SC
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:67:101: error: template argument 2 is invalid
 template<> struct convert_code_from_cv<yarp::sig::PixelHsv> : std::integral_constant<int, CV_BGR2HSV> {};
                                                                                                     ^
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:68:96: error: ‘CV_BGR2HSV’ was not declared in this scope
 template<> struct convert_code_from_cv<yarp::sig::PixelHsvFloat> : std::integral_constant<int, CV_BGR2HSV> {};
                                                                                                ^~~~~~~~~~
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:68:96: note: suggested alternative: ‘CV_32SC’
 template<> struct convert_code_from_cv<yarp::sig::PixelHsvFloat> : std::integral_constant<int, CV_BGR2HSV> {};
                                                                                                ^~~~~~~~~~
                                                                                                CV_32SC
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:68:106: error: template argument 2 is invalid
 template<> struct convert_code_from_cv<yarp::sig::PixelHsvFloat> : std::integral_constant<int, CV_BGR2HSV> {};
                                                                                                          ^
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:69:92: error: ‘CV_BGRA2RGBA’ was not declared in this scope
 template<> struct convert_code_from_cv<yarp::sig::PixelRgba> : std::integral_constant<int, CV_BGRA2RGBA> {};
                                                                                            ^~~~~~~~~~~~
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:69:92: note: suggested alternative: ‘CV_RGB’
 template<> struct convert_code_from_cv<yarp::sig::PixelRgba> : std::integral_constant<int, CV_BGRA2RGBA> {};
                                                                                            ^~~~~~~~~~~~
                                                                                            CV_RGB
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:69:104: error: template argument 2 is invalid
 template<> struct convert_code_from_cv<yarp::sig::PixelRgba> : std::integral_constant<int, CV_BGRA2RGBA> {};
                                                                                                        ^
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp: In member function ‘void stereoCalibThread::stereoCalibRun()’:
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:192:80: error: ‘CV_CALIB_CB_ADAPTIVE_THRESH’ was not declared in this scope
                     foundL = findChessboardCorners(Left, boardSize, pointbufL, CV_CALIB_CB_ADAPTIVE_THRESH | CV_CALIB_CB_FAST_CHECK | CV_CALIB_CB_NORMALIZE_IMAGE);
                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:192:110: error: ‘CV_CALIB_CB_FAST_CHECK’ was not declared in this scope
                     foundL = findChessboardCorners(Left, boardSize, pointbufL, CV_CALIB_CB_ADAPTIVE_THRESH | CV_CALIB_CB_FAST_CHECK | CV_CALIB_CB_NORMALIZE_IMAGE);
                                                                                                              ^~~~~~~~~~~~~~~~~~~~~~
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:192:135: error: ‘CV_CALIB_CB_NORMALIZE_IMAGE’ was not declared in this scope
                     foundL = findChessboardCorners(Left, boardSize, pointbufL, CV_CALIB_CB_ADAPTIVE_THRESH | CV_CALIB_CB_FAST_CHECK | CV_CALIB_CB_NORMALIZE_IMAGE);
                                                                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:197:44: error: ‘CV_RGB2BGR’ was not declared in this scope
                         cvtColor(Left,Left,CV_RGB2BGR);
                                            ^~~~~~~~~~
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:197:44: note: suggested alternative: ‘CV_RGB’
                         cvtColor(Left,Left,CV_RGB2BGR);
                                            ^~~~~~~~~~
                                            CV_RGB
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp: In member function ‘void stereoCalibThread::monoCalibRun()’:
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:314:80: error: ‘CV_CALIB_CB_ADAPTIVE_THRESH’ was not declared in this scope
                     foundL = findChessboardCorners(Left, boardSize, pointbufL, CV_CALIB_CB_ADAPTIVE_THRESH | CV_CALIB_CB_FAST_CHECK | CV_CALIB_CB_NORMALIZE_IMAGE);
                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:314:110: error: ‘CV_CALIB_CB_FAST_CHECK’ was not declared in this scope
                     foundL = findChessboardCorners(Left, boardSize, pointbufL, CV_CALIB_CB_ADAPTIVE_THRESH | CV_CALIB_CB_FAST_CHECK | CV_CALIB_CB_NORMALIZE_IMAGE);
                                                                                                              ^~~~~~~~~~~~~~~~~~~~~~
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:314:135: error: ‘CV_CALIB_CB_NORMALIZE_IMAGE’ was not declared in this scope
                     foundL = findChessboardCorners(Left, boardSize, pointbufL, CV_CALIB_CB_ADAPTIVE_THRESH | CV_CALIB_CB_FAST_CHECK | CV_CALIB_CB_NORMALIZE_IMAGE);
                                                                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:318:44: error: ‘CV_RGB2BGR’ was not declared in this scope
                         cvtColor(Left,Left,CV_RGB2BGR);
                                            ^~~~~~~~~~
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:318:44: note: suggested alternative: ‘CV_RGB’
                         cvtColor(Left,Left,CV_RGB2BGR);
                                            ^~~~~~~~~~
                                            CV_RGB
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp: In member function ‘void stereoCalibThread::monoCalibration(const std::vector<std::__cxx11::basic_string<char> >&, int, int, cv::Mat&, cv::Mat&)’:
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:624:35: error: ‘CV_BGR2GRAY’ was not declared in this scope
          cvtColor(view, viewGray, CV_BGR2GRAY);
                                   ^~~~~~~~~~~
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:633:45: error: ‘CV_CALIB_CB_ADAPTIVE_THRESH’ was not declared in this scope
                                             CV_CALIB_CB_ADAPTIVE_THRESH | CV_CALIB_CB_FAST_CHECK | CV_CALIB_CB_NORMALIZE_IMAGE);
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:633:75: error: ‘CV_CALIB_CB_FAST_CHECK’ was not declared in this scope
                                             CV_CALIB_CB_ADAPTIVE_THRESH | CV_CALIB_CB_FAST_CHECK | CV_CALIB_CB_NORMALIZE_IMAGE);
                                                                           ^~~~~~~~~~~~~~~~~~~~~~
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:633:100: error: ‘CV_CALIB_CB_NORMALIZE_IMAGE’ was not declared in this scope
                                             CV_CALIB_CB_ADAPTIVE_THRESH | CV_CALIB_CB_FAST_CHECK | CV_CALIB_CB_NORMALIZE_IMAGE);
                                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:648:17: error: ‘CV_CALIB_FIX_ASPECT_RATIO’ was not declared in this scope
     if( flags & CV_CALIB_FIX_ASPECT_RATIO )
                 ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:658:40: error: ‘CV_CALIB_FIX_K3’ was not declared in this scope
                     Dist, rvecs, tvecs,CV_CALIB_FIX_K3);
                                        ^~~~~~~~~~~~~~~
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp: In member function ‘void stereoCalibThread::stereoCalibration(const std::vector<std::__cxx11::basic_string<char> >&, int, int, float)’:
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:718:51: error: ‘CV_CALIB_CB_ADAPTIVE_THRESH’ was not declared in this scope
                                                   CV_CALIB_CB_ADAPTIVE_THRESH | CV_CALIB_CB_NORMALIZE_IMAGE);
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:718:81: error: ‘CV_CALIB_CB_NORMALIZE_IMAGE’ was not declared in this scope
                                                   CV_CALIB_CB_ADAPTIVE_THRESH | CV_CALIB_CB_NORMALIZE_IMAGE);
                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:768:25: error: ‘CV_CALIB_FIX_ASPECT_RATIO’ was not declared in this scope
                         CV_CALIB_FIX_ASPECT_RATIO + CV_CALIB_ZERO_TANGENT_DIST + CV_CALIB_SAME_FOCAL_LENGTH + CV_CALIB_FIX_K3,
                         ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:768:53: error: ‘CV_CALIB_ZERO_TANGENT_DIST’ was not declared in this scope
                         CV_CALIB_FIX_ASPECT_RATIO + CV_CALIB_ZERO_TANGENT_DIST + CV_CALIB_SAME_FOCAL_LENGTH + CV_CALIB_FIX_K3,
                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:768:82: error: ‘CV_CALIB_SAME_FOCAL_LENGTH’ was not declared in this scope
                         CV_CALIB_FIX_ASPECT_RATIO + CV_CALIB_ZERO_TANGENT_DIST + CV_CALIB_SAME_FOCAL_LENGTH + CV_CALIB_FIX_K3,
                                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:768:111: error: ‘CV_CALIB_FIX_K3’ was not declared in this scope
                         CV_CALIB_FIX_ASPECT_RATIO + CV_CALIB_ZERO_TANGENT_DIST + CV_CALIB_SAME_FOCAL_LENGTH + CV_CALIB_FIX_K3,
                                                                                                               ^~~~~~~~~~~~~~~
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:782:18: error: ‘CV_CALIB_FIX_ASPECT_RATIO’ was not declared in this scope
                  CV_CALIB_FIX_ASPECT_RATIO + CV_CALIB_FIX_INTRINSIC + CV_CALIB_FIX_K3);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:782:46: error: ‘CV_CALIB_FIX_INTRINSIC’ was not declared in this scope
                  CV_CALIB_FIX_ASPECT_RATIO + CV_CALIB_FIX_INTRINSIC + CV_CALIB_FIX_K3);
                                              ^~~~~~~~~~~~~~~~~~~~~~
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:782:71: error: ‘CV_CALIB_FIX_K3’ was not declared in this scope
                  CV_CALIB_FIX_ASPECT_RATIO + CV_CALIB_FIX_INTRINSIC + CV_CALIB_FIX_K3);
                                                                       ^~~~~~~~~~~~~~~
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp: In member function ‘void stereoCalibThread::saveCalibration(const string&, const string&)’:
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:833:46: error: ‘CV_STORAGE_WRITE’ was not declared in this scope
     FileStorage fs(intrinsicFilePath+".yml", CV_STORAGE_WRITE);
                                              ^~~~~~~~~~~~~~~~
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:833:46: note: suggested alternative: ‘VOCAB_WHITE’
     FileStorage fs(intrinsicFilePath+".yml", CV_STORAGE_WRITE);
                                              ^~~~~~~~~~~~~~~~
                                              VOCAB_WHITE
In file included from /home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv.h:60:0,
                 from /home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:2:
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h: In instantiation of ‘cv::Mat yarp::cv::toCvMat(yarp::sig::ImageOf<T>&) [with T = yarp::sig::PixelRgb]’:
/home/pmurali/icub-main/src/tools/stereoCalib/src/stereoCalibThread.cpp:180:47:   required from here
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:82:38: error: ‘value’ is not a member of ‘yarp::cv::convert_code_to_cv<yarp::sig::PixelRgb>’
     if (convert_code_to_cv<T>::value >= 0)
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/home/pmurali/yarp/src/libYARP_cv/include/yarp/cv/Cv-inl.h:84:23: error: ‘value’ is not a member of ‘yarp::cv::convert_code_to_cv<yarp::sig::PixelRgb>’
         ::cv::cvtColor(outMat, outMat, convert_code_to_cv<T>::value);
         ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/tools/stereoCalib/CMakeFiles/stereoCalib.dir/build.make:110: recipe for target 'src/tools/stereoCalib/CMakeFiles/stereoCalib.dir/src/stereoCalibThread.cpp.o' failed
make[2]: *** [src/tools/stereoCalib/CMakeFiles/stereoCalib.dir/src/stereoCalibThread.cpp.o] Error 1
CMakeFiles/Makefile2:3375: recipe for target 'src/tools/stereoCalib/CMakeFiles/stereoCalib.dir/all' failed
make[1]: *** [src/tools/stereoCalib/CMakeFiles/stereoCalib.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

However build is fine with
```
 ICUB_USE_OpenCV                  OFF                                                                                                                                 
 ICUB_USE_OpenGL                  OFF 
```
My OpenCV version: 4.1.0

CC: @traversaro

**Comment by traversaro** [comment] 2019-11-08 12:26
Hi Praj, unfortunatly the fact that OpenCV 4 is not supported on YARP/ICUB and the related stack is a known issue, see https://github.com/robotology/yarp/issues/1672 . If you need to compile in a system with OpenCV, I suggest to disable the `ICUB_USE_OpenCV`.

**Comment by traversaro** [comment] 2019-11-08 12:27
As the issue is tracked in https://github.com/robotology/yarp/issues/1672 , I will close the issue, thanks in any case for reporting.

**Closed** 2019-11-08 12:27 UTC

**Comment by prajval10** [comment] 2019-11-08 13:11
> Hi Praj, unfortunatly the fact that OpenCV 4 is not supported on YARP/ICUB and the related stack is a known issue, see [robotology/yarp#1672](https://github.com/robotology/yarp/issues/1672) . If you need to compile in a system with OpenCV, I suggest to disable the `ICUB_USE_OpenCV`.

Got it. Thanks! :+1:
