### ISSUE TITLE
Porting Joypad to SDL2

### ISSUE THREAD

**Issue by drdanz** [robotology/icub-main#449] opened 2017-05-24 15:07 UTC
We should port the joypad driver to SDL2 since SDL1 is not supported on vcpkg, I made a few tests and the only calls to replace seem to be  `SDL_JoystickName` -> `SDL_JoystickNameForIndex`.
Unfortunately there is also some weird linking issue to fix.

**Comment by drdanz** [comment] 2017-11-02 13:32
+1

**Comment by randaz81** [comment] 2017-11-06 09:38
Absolutely no!

**Comment by drdanz** [comment] 2017-11-07 11:36
@randaz81 deprecate != remove.
If we don't deprecate it, new modules will be created using the old driver

**Comment by randaz81** [comment] 2017-11-07 12:52
We are not speaking of a driver. It's a user module. So far, no modules was ever removed by a robotology repo. Simply you don't use it....

**Comment by drdanz** [comment] 2017-11-09 07:18
Sorry, I thought we were speaking about a device, not a user module...

**Comment by aerydna** [comment] 2017-11-09 17:33
the problem is that old module ( replaceable by a new device ) should not be maintain, and so in this case ported to SDL2. In my opinion this issue should be closed with a `won't fix`.

**Closed** 2018-02-12 14:35 UTC
Labels: IFI Day reviewed, Resolution: Fixed, Type: Task
